path: C:/Users/10107/Desktop/yolov8/Machine Learning/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: person
  1: wolf
